version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
